-- Script was generated by Devart dbForge Studio Express for MySQL, Version 5.0.76.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 06/08/2012 02:35:24 a.m.
-- Server version: 5.5.24-log
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE opencart;

--
-- Definition for table oc_affiliate
--
CREATE TABLE oc_affiliate (
  affiliate_id INT(11) NOT NULL AUTO_INCREMENT,
  firstname VARCHAR(32) NOT NULL DEFAULT '',
  lastname VARCHAR(32) NOT NULL DEFAULT '',
  email VARCHAR(96) NOT NULL DEFAULT '',
  telephone VARCHAR(32) NOT NULL DEFAULT '',
  fax VARCHAR(32) NOT NULL DEFAULT '',
  `password` VARCHAR(40) NOT NULL DEFAULT '',
  company VARCHAR(32) NOT NULL,
  website VARCHAR(255) NOT NULL,
  address_1 VARCHAR(128) NOT NULL DEFAULT '',
  address_2 VARCHAR(128) NOT NULL,
  city VARCHAR(128) NOT NULL DEFAULT '',
  postcode VARCHAR(10) NOT NULL DEFAULT '',
  country_id INT(11) NOT NULL,
  zone_id INT(11) NOT NULL,
  code VARCHAR(64) NOT NULL,
  commission DECIMAL(4, 2) NOT NULL DEFAULT 0.00,
  tax VARCHAR(64) NOT NULL,
  payment VARCHAR(6) NOT NULL,
  cheque VARCHAR(100) NOT NULL DEFAULT '',
  paypal VARCHAR(64) NOT NULL DEFAULT '',
  bank_name VARCHAR(64) NOT NULL DEFAULT '',
  bank_branch_number VARCHAR(64) NOT NULL DEFAULT '',
  bank_swift_code VARCHAR(64) NOT NULL DEFAULT '',
  bank_account_name VARCHAR(64) NOT NULL DEFAULT '',
  bank_account_number VARCHAR(64) NOT NULL DEFAULT '',
  ip VARCHAR(15) NOT NULL,
  status TINYINT(1) NOT NULL DEFAULT 0,
  approved TINYINT(1) NOT NULL DEFAULT 0,
  date_added DATETIME NOT NULL,
  PRIMARY KEY (affiliate_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_attribute_group
--
CREATE TABLE oc_attribute_group (
  attribute_group_id INT(11) NOT NULL AUTO_INCREMENT,
  sort_order INT(3) NOT NULL,
  PRIMARY KEY (attribute_group_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 7
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_banner
--
CREATE TABLE oc_banner (
  banner_id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL,
  status TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (banner_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 9
AVG_ROW_LENGTH = 5461
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_category
--
CREATE TABLE oc_category (
  category_id INT(11) NOT NULL AUTO_INCREMENT,
  image VARCHAR(255) DEFAULT NULL,
  parent_id INT(11) DEFAULT NULL,
  top TINYINT(1) NOT NULL DEFAULT 0,
  `column` INT(3) NOT NULL,
  sort_order INT(3) NOT NULL DEFAULT 0,
  status TINYINT(1) NOT NULL DEFAULT 0,
  date_added DATETIME NOT NULL,
  date_modified DATETIME NOT NULL,
  PRIMARY KEY (category_id),
  CONSTRAINT fk_category_category FOREIGN KEY (parent_id)
    REFERENCES oc_category(category_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 59
AVG_ROW_LENGTH = 431
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_country
--
CREATE TABLE oc_country (
  country_id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(128) NOT NULL,
  iso_code_2 VARCHAR(2) NOT NULL DEFAULT '',
  iso_code_3 VARCHAR(3) NOT NULL DEFAULT '',
  address_format TEXT NOT NULL,
  postcode_required TINYINT(1) NOT NULL DEFAULT 0,
  status TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (country_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 240
AVG_ROW_LENGTH = 68
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_coupon
--
CREATE TABLE oc_coupon (
  coupon_id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(128) NOT NULL,
  code VARCHAR(10) NOT NULL,
  type CHAR(1) NOT NULL,
  discount DECIMAL(15, 4) NOT NULL,
  logged TINYINT(1) NOT NULL DEFAULT 0,
  shipping TINYINT(1) NOT NULL DEFAULT 0,
  total DECIMAL(15, 4) NOT NULL,
  date_start DATE NOT NULL,
  date_end DATE NOT NULL,
  uses_total INT(11) NOT NULL,
  uses_customer VARCHAR(11) NOT NULL,
  status TINYINT(1) NOT NULL DEFAULT 0,
  date_added DATETIME NOT NULL,
  PRIMARY KEY (coupon_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 7
AVG_ROW_LENGTH = 5461
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_currency
--
CREATE TABLE oc_currency (
  currency_id INT(11) NOT NULL AUTO_INCREMENT,
  title VARCHAR(32) NOT NULL DEFAULT '',
  code VARCHAR(3) NOT NULL DEFAULT '',
  symbol_left VARCHAR(12) NOT NULL,
  symbol_right VARCHAR(12) NOT NULL,
  decimal_place CHAR(1) NOT NULL,
  value FLOAT(15, 8) NOT NULL,
  status TINYINT(1) NOT NULL DEFAULT 0,
  date_modified DATETIME NOT NULL,
  PRIMARY KEY (currency_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 4
AVG_ROW_LENGTH = 5461
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_customer_group
--
CREATE TABLE oc_customer_group (
  customer_group_id INT(11) NOT NULL AUTO_INCREMENT,
  approval INT(1) NOT NULL,
  company_id_display INT(1) NOT NULL,
  company_id_required INT(1) NOT NULL,
  tax_id_display INT(1) NOT NULL,
  tax_id_required INT(1) NOT NULL,
  sort_order INT(3) NOT NULL,
  PRIMARY KEY (customer_group_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 9
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_customer_ip_blacklist
--
CREATE TABLE oc_customer_ip_blacklist (
  customer_ip_blacklist_id INT(11) NOT NULL AUTO_INCREMENT,
  ip VARCHAR(15) NOT NULL DEFAULT '',
  PRIMARY KEY (customer_ip_blacklist_id),
  INDEX ip (ip)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_customer_online
--
CREATE TABLE oc_customer_online (
  ip BIGINT(10) NOT NULL,
  customer_id INT(11) NOT NULL,
  url TEXT NOT NULL,
  referer TEXT NOT NULL,
  date_added DATETIME NOT NULL,
  PRIMARY KEY (ip)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_customer_reward
--
CREATE TABLE oc_customer_reward (
  customer_reward_id INT(11) NOT NULL AUTO_INCREMENT,
  customer_id INT(11) NOT NULL DEFAULT 0,
  order_id INT(11) NOT NULL DEFAULT 0,
  description TEXT NOT NULL,
  points INT(8) NOT NULL DEFAULT 0,
  date_added DATETIME NOT NULL,
  PRIMARY KEY (customer_reward_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_customer_transaction
--
CREATE TABLE oc_customer_transaction (
  customer_transaction_id INT(11) NOT NULL AUTO_INCREMENT,
  customer_id INT(11) NOT NULL,
  order_id INT(11) NOT NULL,
  description TEXT NOT NULL,
  amount DECIMAL(15, 4) NOT NULL,
  date_added DATETIME NOT NULL,
  PRIMARY KEY (customer_transaction_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_download
--
CREATE TABLE oc_download (
  download_id INT(11) NOT NULL AUTO_INCREMENT,
  filename VARCHAR(128) NOT NULL DEFAULT '',
  mask VARCHAR(128) NOT NULL DEFAULT '',
  remaining INT(11) NOT NULL DEFAULT 0,
  date_added DATETIME NOT NULL,
  PRIMARY KEY (download_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_extension
--
CREATE TABLE oc_extension (
  extension_id INT(11) NOT NULL AUTO_INCREMENT,
  type VARCHAR(32) NOT NULL,
  code VARCHAR(32) NOT NULL,
  PRIMARY KEY (extension_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 428
AVG_ROW_LENGTH = 819
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_geo_zone
--
CREATE TABLE oc_geo_zone (
  geo_zone_id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(32) NOT NULL DEFAULT '',
  description VARCHAR(255) NOT NULL DEFAULT '',
  date_modified DATETIME NOT NULL,
  date_added DATETIME NOT NULL,
  PRIMARY KEY (geo_zone_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 5
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_information
--
CREATE TABLE oc_information (
  information_id INT(11) NOT NULL AUTO_INCREMENT,
  bottom INT(1) NOT NULL DEFAULT 0,
  sort_order INT(3) NOT NULL DEFAULT 0,
  status TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (information_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 7
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_language
--
CREATE TABLE oc_language (
  language_id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(32) NOT NULL DEFAULT '',
  code VARCHAR(5) NOT NULL,
  locale VARCHAR(255) NOT NULL,
  image VARCHAR(64) NOT NULL,
  `directory` VARCHAR(32) NOT NULL DEFAULT '',
  filename VARCHAR(64) NOT NULL DEFAULT '',
  sort_order INT(3) NOT NULL DEFAULT 0,
  status TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (language_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_layout
--
CREATE TABLE oc_layout (
  layout_id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL,
  PRIMARY KEY (layout_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 12
AVG_ROW_LENGTH = 1489
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_length_class
--
CREATE TABLE oc_length_class (
  length_class_id INT(11) NOT NULL AUTO_INCREMENT,
  value DECIMAL(15, 8) NOT NULL,
  PRIMARY KEY (length_class_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 4
AVG_ROW_LENGTH = 5461
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_manufacturer
--
CREATE TABLE oc_manufacturer (
  manufacturer_id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL DEFAULT '',
  image VARCHAR(255) DEFAULT NULL,
  sort_order INT(3) NOT NULL,
  PRIMARY KEY (manufacturer_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 11
AVG_ROW_LENGTH = 2730
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_option
--
CREATE TABLE oc_option (
  option_id INT(11) NOT NULL AUTO_INCREMENT,
  type VARCHAR(32) NOT NULL,
  sort_order INT(3) NOT NULL,
  PRIMARY KEY (option_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 13
AVG_ROW_LENGTH = 1489
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_order_fraud
--
CREATE TABLE oc_order_fraud (
  order_id INT(11) NOT NULL,
  customer_id INT(11) NOT NULL,
  country_match VARCHAR(3) NOT NULL,
  country_code VARCHAR(2) NOT NULL,
  high_risk_country VARCHAR(3) NOT NULL,
  distance INT(11) NOT NULL,
  ip_region VARCHAR(255) NOT NULL,
  ip_city VARCHAR(255) NOT NULL,
  ip_latitude DECIMAL(10, 6) NOT NULL,
  ip_longitude DECIMAL(10, 6) NOT NULL,
  ip_isp VARCHAR(255) NOT NULL,
  ip_org VARCHAR(255) NOT NULL,
  ip_asnum INT(11) NOT NULL,
  ip_user_type VARCHAR(255) NOT NULL,
  ip_country_confidence VARCHAR(3) NOT NULL,
  ip_region_confidence VARCHAR(3) NOT NULL,
  ip_city_confidence VARCHAR(3) NOT NULL,
  ip_postal_confidence VARCHAR(3) NOT NULL,
  ip_postal_code VARCHAR(10) NOT NULL,
  ip_accuracy_radius INT(11) NOT NULL,
  ip_net_speed_cell VARCHAR(255) NOT NULL,
  ip_metro_code INT(3) NOT NULL,
  ip_area_code INT(3) NOT NULL,
  ip_time_zone VARCHAR(255) NOT NULL,
  ip_region_name VARCHAR(255) NOT NULL,
  ip_domain VARCHAR(255) NOT NULL,
  ip_country_name VARCHAR(255) NOT NULL,
  ip_continent_code VARCHAR(2) NOT NULL,
  ip_corporate_proxy VARCHAR(3) NOT NULL,
  anonymous_proxy VARCHAR(3) NOT NULL,
  proxy_score INT(3) NOT NULL,
  is_trans_proxy VARCHAR(3) NOT NULL,
  free_mail VARCHAR(3) NOT NULL,
  carder_email VARCHAR(3) NOT NULL,
  high_risk_username VARCHAR(3) NOT NULL,
  high_risk_password VARCHAR(3) NOT NULL,
  bin_match VARCHAR(10) NOT NULL,
  bin_country VARCHAR(2) NOT NULL,
  bin_name_match VARCHAR(3) NOT NULL,
  bin_name VARCHAR(255) NOT NULL,
  bin_phone_match VARCHAR(3) NOT NULL,
  bin_phone VARCHAR(32) NOT NULL,
  customer_phone_in_billing_location VARCHAR(8) NOT NULL,
  ship_forward VARCHAR(3) NOT NULL,
  city_postal_match VARCHAR(3) NOT NULL,
  ship_city_postal_match VARCHAR(3) NOT NULL,
  score DECIMAL(10, 5) NOT NULL,
  explanation TEXT NOT NULL,
  risk_score DECIMAL(10, 5) NOT NULL,
  queries_remaining INT(11) NOT NULL,
  maxmind_id VARCHAR(8) NOT NULL,
  error TEXT NOT NULL,
  date_added DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (order_id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_order_misc
--
CREATE TABLE oc_order_misc (
  order_id INT(11) NOT NULL DEFAULT 0,
  `key` VARCHAR(64) NOT NULL,
  value TEXT NOT NULL,
  PRIMARY KEY (order_id, `key`)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_order_voucher
--
CREATE TABLE oc_order_voucher (
  order_voucher_id INT(11) NOT NULL AUTO_INCREMENT,
  order_id INT(11) NOT NULL,
  voucher_id INT(11) NOT NULL,
  description VARCHAR(255) NOT NULL,
  code VARCHAR(10) NOT NULL,
  from_name VARCHAR(64) NOT NULL,
  from_email VARCHAR(96) NOT NULL,
  to_name VARCHAR(64) NOT NULL,
  to_email VARCHAR(96) NOT NULL,
  voucher_theme_id INT(11) NOT NULL,
  message TEXT NOT NULL,
  amount DECIMAL(15, 4) NOT NULL,
  PRIMARY KEY (order_voucher_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_setting
--
CREATE TABLE oc_setting (
  setting_id INT(11) NOT NULL AUTO_INCREMENT,
  store_id INT(11) NOT NULL,
  `group` VARCHAR(32) NOT NULL,
  `key` VARCHAR(64) NOT NULL DEFAULT '',
  value TEXT NOT NULL,
  serialized TINYINT(1) NOT NULL,
  PRIMARY KEY (setting_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 24298
AVG_ROW_LENGTH = 3276
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_store
--
CREATE TABLE oc_store (
  store_id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL,
  url VARCHAR(255) NOT NULL,
  `ssl` VARCHAR(255) NOT NULL,
  PRIMARY KEY (store_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_tax_class
--
CREATE TABLE oc_tax_class (
  tax_class_id INT(11) NOT NULL AUTO_INCREMENT,
  title VARCHAR(32) NOT NULL DEFAULT '',
  description VARCHAR(255) NOT NULL DEFAULT '',
  date_added DATETIME NOT NULL,
  date_modified DATETIME NOT NULL,
  PRIMARY KEY (tax_class_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 11
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_url_alias
--
CREATE TABLE oc_url_alias (
  url_alias_id INT(11) NOT NULL AUTO_INCREMENT,
  query VARCHAR(255) NOT NULL,
  keyword VARCHAR(255) NOT NULL,
  PRIMARY KEY (url_alias_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 774
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_user_group
--
CREATE TABLE oc_user_group (
  user_group_id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL,
  permission TEXT NOT NULL,
  PRIMARY KEY (user_group_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 11
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_voucher_theme
--
CREATE TABLE oc_voucher_theme (
  voucher_theme_id INT(11) NOT NULL AUTO_INCREMENT,
  image VARCHAR(255) NOT NULL,
  PRIMARY KEY (voucher_theme_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 9
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_weight_class
--
CREATE TABLE oc_weight_class (
  weight_class_id INT(11) NOT NULL AUTO_INCREMENT,
  value DECIMAL(15, 8) NOT NULL DEFAULT 0.00000000,
  PRIMARY KEY (weight_class_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 7
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_attribute
--
CREATE TABLE oc_attribute (
  attribute_id INT(11) NOT NULL AUTO_INCREMENT,
  attribute_group_id INT(11) NOT NULL,
  sort_order INT(3) NOT NULL,
  PRIMARY KEY (attribute_id),
  CONSTRAINT fk_attribute_attribute_group FOREIGN KEY (attribute_group_id)
    REFERENCES oc_attribute_group(attribute_group_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 12
AVG_ROW_LENGTH = 1489
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_attribute_group_description
--
CREATE TABLE oc_attribute_group_description (
  attribute_group_id INT(11) NOT NULL,
  language_id INT(11) NOT NULL,
  name VARCHAR(64) NOT NULL,
  CONSTRAINT fk_attribute_group_description_attribute_group FOREIGN KEY (attribute_group_id)
    REFERENCES oc_attribute_group(attribute_group_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_attribute_group_description_language FOREIGN KEY (language_id)
    REFERENCES oc_language(language_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_banner_image
--
CREATE TABLE oc_banner_image (
  banner_image_id INT(11) NOT NULL AUTO_INCREMENT,
  banner_id INT(11) NOT NULL,
  link VARCHAR(255) NOT NULL,
  image VARCHAR(255) NOT NULL,
  PRIMARY KEY (banner_image_id),
  CONSTRAINT fk_banner_image_banner FOREIGN KEY (banner_id)
    REFERENCES oc_banner(banner_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 78
AVG_ROW_LENGTH = 2048
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_banner_image_description
--
CREATE TABLE oc_banner_image_description (
  banner_image_id INT(11) NOT NULL,
  language_id INT(11) NOT NULL,
  banner_id INT(11) NOT NULL,
  title VARCHAR(64) NOT NULL,
  PRIMARY KEY (banner_image_id),
  CONSTRAINT fk_banner_image_description_banner FOREIGN KEY (banner_id)
    REFERENCES oc_banner(banner_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_banner_image_description_language FOREIGN KEY (language_id)
    REFERENCES oc_language(language_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AVG_ROW_LENGTH = 2048
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_category_description
--
CREATE TABLE oc_category_description (
  category_id INT(11) NOT NULL,
  language_id INT(11) NOT NULL,
  name VARCHAR(255) NOT NULL DEFAULT '',
  description TEXT NOT NULL,
  meta_description VARCHAR(255) NOT NULL,
  meta_keyword VARCHAR(255) NOT NULL,
  INDEX name (name),
  CONSTRAINT fk_category_description_category FOREIGN KEY (category_id)
    REFERENCES oc_category(category_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_category_description_language FOREIGN KEY (language_id)
    REFERENCES oc_language(language_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AVG_ROW_LENGTH = 431
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_category_to_layout
--
CREATE TABLE oc_category_to_layout (
  category_id INT(11) NOT NULL,
  store_id INT(11) NOT NULL,
  layout_id INT(11) NOT NULL,
  CONSTRAINT fk_category_to_layout_category FOREIGN KEY (category_id)
    REFERENCES oc_category(category_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_category_to_layout_layout FOREIGN KEY (layout_id)
    REFERENCES oc_layout(layout_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_category_to_layout_store FOREIGN KEY (store_id)
    REFERENCES oc_store(store_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_category_to_store
--
CREATE TABLE oc_category_to_store (
  category_id INT(11) NOT NULL,
  store_id INT(11) NOT NULL,
  CONSTRAINT fk_category_to_store_category FOREIGN KEY (category_id)
    REFERENCES oc_category(category_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_category_to_store_store FOREIGN KEY (store_id)
    REFERENCES oc_store(store_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AVG_ROW_LENGTH = 431
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_customer
--
CREATE TABLE oc_customer (
  customer_id INT(11) NOT NULL AUTO_INCREMENT,
  customer_group_id INT(11) NOT NULL,
  store_id INT(11) NOT NULL DEFAULT 0,
  firstname VARCHAR(32) NOT NULL DEFAULT '',
  lastname VARCHAR(32) NOT NULL DEFAULT '',
  email VARCHAR(96) NOT NULL DEFAULT '',
  telephone VARCHAR(32) NOT NULL DEFAULT '',
  fax VARCHAR(32) NOT NULL DEFAULT '',
  `password` VARCHAR(40) NOT NULL DEFAULT '',
  cart TEXT DEFAULT NULL,
  wishlist TEXT DEFAULT NULL,
  newsletter TINYINT(1) NOT NULL DEFAULT 0,
  address_id INT(11) NOT NULL DEFAULT 0,
  ip VARCHAR(15) NOT NULL DEFAULT '0',
  status TINYINT(1) NOT NULL DEFAULT 0,
  approved TINYINT(1) NOT NULL DEFAULT 0,
  token VARCHAR(255) NOT NULL,
  date_added DATETIME NOT NULL,
  PRIMARY KEY (customer_id),
  INDEX fk_customer_customer_group (customer_group_id),
  CONSTRAINT fk_customer_customer_group1 FOREIGN KEY (customer_group_id)
    REFERENCES oc_customer_group(customer_group_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_customer_store FOREIGN KEY (store_id)
    REFERENCES oc_store(store_id) ON DELETE NO ACTION ON UPDATE NO ACTION
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_customer_group_description
--
CREATE TABLE oc_customer_group_description (
  customer_group_id INT(11) NOT NULL,
  language_id INT(11) NOT NULL,
  name VARCHAR(32) NOT NULL,
  description TEXT NOT NULL,
  PRIMARY KEY (customer_group_id, language_id),
  CONSTRAINT fk_customer_group_description_language FOREIGN KEY (language_id)
    REFERENCES oc_language(language_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_download_description
--
CREATE TABLE oc_download_description (
  download_id INT(11) NOT NULL,
  language_id INT(11) NOT NULL,
  name VARCHAR(64) NOT NULL DEFAULT '',
  CONSTRAINT fk_download_description_download FOREIGN KEY (download_id)
    REFERENCES oc_download(download_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_download_description_language FOREIGN KEY (language_id)
    REFERENCES oc_language(language_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_information_description
--
CREATE TABLE oc_information_description (
  information_id INT(11) NOT NULL,
  language_id INT(11) NOT NULL,
  title VARCHAR(64) NOT NULL DEFAULT '',
  description TEXT NOT NULL,
  CONSTRAINT fk_information_description_information FOREIGN KEY (information_id)
    REFERENCES oc_information(information_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_information_description_language FOREIGN KEY (language_id)
    REFERENCES oc_language(language_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_information_to_layout
--
CREATE TABLE oc_information_to_layout (
  information_id INT(11) NOT NULL,
  store_id INT(11) NOT NULL,
  layout_id INT(11) NOT NULL,
  CONSTRAINT fk_information_to_layout_information FOREIGN KEY (information_id)
    REFERENCES oc_information(information_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_information_to_layout_layout FOREIGN KEY (layout_id)
    REFERENCES oc_layout(layout_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_information_to_layout_store FOREIGN KEY (store_id)
    REFERENCES oc_store(store_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_information_to_store
--
CREATE TABLE oc_information_to_store (
  information_id INT(11) NOT NULL,
  store_id INT(11) NOT NULL,
  CONSTRAINT fk_information_to_store_information FOREIGN KEY (information_id)
    REFERENCES oc_information(information_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_information_to_store_store FOREIGN KEY (store_id)
    REFERENCES oc_store(store_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_layout_route
--
CREATE TABLE oc_layout_route (
  layout_route_id INT(11) NOT NULL AUTO_INCREMENT,
  layout_id INT(11) NOT NULL,
  store_id INT(11) NOT NULL,
  route VARCHAR(255) NOT NULL,
  PRIMARY KEY (layout_route_id),
  CONSTRAINT fk_layout_route_layout FOREIGN KEY (layout_id)
    REFERENCES oc_layout(layout_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_layout_route_store FOREIGN KEY (store_id)
    REFERENCES oc_store(store_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 32
AVG_ROW_LENGTH = 1820
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_length_class_description
--
CREATE TABLE oc_length_class_description (
  length_class_id INT(11) NOT NULL,
  language_id INT(11) NOT NULL,
  title VARCHAR(32) NOT NULL,
  unit VARCHAR(4) NOT NULL,
  CONSTRAINT fk_length_class_description_language FOREIGN KEY (language_id)
    REFERENCES oc_language(language_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_length_class_description_length_class FOREIGN KEY (length_class_id)
    REFERENCES oc_length_class(length_class_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AVG_ROW_LENGTH = 5461
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_manufacturer_to_store
--
CREATE TABLE oc_manufacturer_to_store (
  manufacturer_id INT(11) NOT NULL,
  store_id INT(11) NOT NULL,
  CONSTRAINT fk_manufacturer_to_store_manufacturer FOREIGN KEY (manufacturer_id)
    REFERENCES oc_manufacturer(manufacturer_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_manufacturer_to_store_store FOREIGN KEY (store_id)
    REFERENCES oc_store(store_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AVG_ROW_LENGTH = 2730
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_option_description
--
CREATE TABLE oc_option_description (
  option_id INT(11) NOT NULL,
  language_id INT(11) NOT NULL,
  name VARCHAR(128) NOT NULL,
  CONSTRAINT fk_option_description_language FOREIGN KEY (language_id)
    REFERENCES oc_language(language_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_option_description_option FOREIGN KEY (option_id)
    REFERENCES oc_option(option_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AVG_ROW_LENGTH = 1489
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_option_value
--
CREATE TABLE oc_option_value (
  option_value_id INT(11) NOT NULL AUTO_INCREMENT,
  option_id INT(11) NOT NULL,
  image VARCHAR(255) NOT NULL,
  sort_order INT(3) NOT NULL,
  PRIMARY KEY (option_value_id),
  CONSTRAINT fk_option_value_option FOREIGN KEY (option_id)
    REFERENCES oc_option(option_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 49
AVG_ROW_LENGTH = 1170
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_order_status
--
CREATE TABLE oc_order_status (
  order_status_id INT(11) NOT NULL AUTO_INCREMENT,
  language_id INT(11) NOT NULL,
  name VARCHAR(32) NOT NULL,
  PRIMARY KEY (order_status_id),
  CONSTRAINT fk_order_status_language FOREIGN KEY (language_id)
    REFERENCES oc_language(language_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 17
AVG_ROW_LENGTH = 1170
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_return_action
--
CREATE TABLE oc_return_action (
  return_action_id INT(11) NOT NULL AUTO_INCREMENT,
  language_id INT(11) NOT NULL DEFAULT 0,
  name VARCHAR(64) NOT NULL DEFAULT '',
  PRIMARY KEY (return_action_id),
  CONSTRAINT fk_return_action_language FOREIGN KEY (language_id)
    REFERENCES oc_language(language_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 4
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_return_reason
--
CREATE TABLE oc_return_reason (
  return_reason_id INT(11) NOT NULL AUTO_INCREMENT,
  language_id INT(11) NOT NULL DEFAULT 0,
  name VARCHAR(128) NOT NULL DEFAULT '',
  PRIMARY KEY (return_reason_id),
  CONSTRAINT fk_return_reason_language FOREIGN KEY (language_id)
    REFERENCES oc_language(language_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 6
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_return_status
--
CREATE TABLE oc_return_status (
  return_status_id INT(11) NOT NULL AUTO_INCREMENT,
  language_id INT(11) NOT NULL DEFAULT 0,
  name VARCHAR(32) NOT NULL DEFAULT '',
  PRIMARY KEY (return_status_id),
  CONSTRAINT fk_return_status_language FOREIGN KEY (language_id)
    REFERENCES oc_language(language_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 4
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_stock_status
--
CREATE TABLE oc_stock_status (
  stock_status_id INT(11) NOT NULL AUTO_INCREMENT,
  language_id INT(11) NOT NULL,
  name VARCHAR(32) NOT NULL,
  PRIMARY KEY (stock_status_id),
  CONSTRAINT fk_stock_status_language FOREIGN KEY (language_id)
    REFERENCES oc_language(language_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 9
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_tax_rate
--
CREATE TABLE oc_tax_rate (
  tax_rate_id INT(11) NOT NULL AUTO_INCREMENT,
  geo_zone_id INT(11) NOT NULL,
  name VARCHAR(32) NOT NULL,
  rate DECIMAL(15, 4) NOT NULL DEFAULT 0.0000,
  type CHAR(1) NOT NULL,
  date_added DATETIME NOT NULL,
  date_modified DATETIME NOT NULL,
  PRIMARY KEY (tax_rate_id),
  CONSTRAINT fk_tax_rate_geo_zone FOREIGN KEY (geo_zone_id)
    REFERENCES oc_geo_zone(geo_zone_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 88
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_user
--
CREATE TABLE oc_user (
  user_id INT(11) NOT NULL AUTO_INCREMENT,
  user_group_id INT(11) NOT NULL,
  username VARCHAR(20) NOT NULL DEFAULT '',
  `password` VARCHAR(32) NOT NULL DEFAULT '',
  firstname VARCHAR(32) NOT NULL DEFAULT '',
  lastname VARCHAR(32) NOT NULL DEFAULT '',
  email VARCHAR(96) NOT NULL DEFAULT '',
  code VARCHAR(32) NOT NULL,
  ip VARCHAR(15) NOT NULL DEFAULT '',
  status TINYINT(1) NOT NULL DEFAULT 0,
  date_added DATETIME NOT NULL,
  PRIMARY KEY (user_id),
  CONSTRAINT fk_user_user_group FOREIGN KEY (user_group_id)
    REFERENCES oc_user_group(user_group_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 2
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_voucher_theme_description
--
CREATE TABLE oc_voucher_theme_description (
  voucher_theme_id INT(11) NOT NULL,
  language_id INT(11) NOT NULL,
  name VARCHAR(32) NOT NULL,
  CONSTRAINT fk_voucher_theme_description_language FOREIGN KEY (language_id)
    REFERENCES oc_language(language_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_voucher_theme_description_voucher_theme FOREIGN KEY (voucher_theme_id)
    REFERENCES oc_voucher_theme(voucher_theme_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_weight_class_description
--
CREATE TABLE oc_weight_class_description (
  weight_class_id INT(11) NOT NULL,
  language_id INT(11) NOT NULL,
  title VARCHAR(32) NOT NULL,
  unit VARCHAR(4) NOT NULL,
  CONSTRAINT fk_weight_class_description_language FOREIGN KEY (language_id)
    REFERENCES oc_language(language_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_weight_class_description_weight_class FOREIGN KEY (weight_class_id)
    REFERENCES oc_weight_class(weight_class_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_zone
--
CREATE TABLE oc_zone (
  zone_id INT(11) NOT NULL AUTO_INCREMENT,
  country_id INT(11) NOT NULL,
  code VARCHAR(32) NOT NULL DEFAULT '',
  name VARCHAR(128) NOT NULL,
  status TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (zone_id),
  CONSTRAINT fk_zone_country FOREIGN KEY (country_id)
    REFERENCES oc_country(country_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 3968
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_address
--
CREATE TABLE oc_address (
  address_id INT(11) NOT NULL,
  customer_id INT(11) NOT NULL,
  country_id INT(11) NOT NULL DEFAULT 0,
  zone_id INT(11) NOT NULL DEFAULT 0,
  firstname VARCHAR(32) NOT NULL DEFAULT '',
  lastname VARCHAR(32) NOT NULL DEFAULT '',
  company VARCHAR(32) NOT NULL,
  company_id VARCHAR(32) NOT NULL DEFAULT '',
  tax_id VARCHAR(32) NOT NULL DEFAULT '',
  address_1 VARCHAR(128) NOT NULL,
  address_2 VARCHAR(128) NOT NULL,
  city VARCHAR(128) NOT NULL,
  postcode VARCHAR(10) NOT NULL,
  PRIMARY KEY (address_id),
  CONSTRAINT fk_address_country1 FOREIGN KEY (country_id)
    REFERENCES oc_country(country_id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT fk_address_customer1 FOREIGN KEY (customer_id)
    REFERENCES oc_customer(customer_id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT fk_address_zone1 FOREIGN KEY (zone_id)
    REFERENCES oc_zone(zone_id) ON DELETE NO ACTION ON UPDATE NO ACTION
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_attribute_description
--
CREATE TABLE oc_attribute_description (
  attribute_id INT(11) NOT NULL,
  language_id INT(11) NOT NULL,
  name VARCHAR(64) NOT NULL,
  CONSTRAINT fk_attribute_description_attribute FOREIGN KEY (attribute_id)
    REFERENCES oc_attribute(attribute_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_attribute_description_language FOREIGN KEY (language_id)
    REFERENCES oc_language(language_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AVG_ROW_LENGTH = 1489
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_customer_ip
--
CREATE TABLE oc_customer_ip (
  customer_ip_id INT(11) NOT NULL AUTO_INCREMENT,
  customer_id INT(11) NOT NULL,
  ip VARCHAR(15) NOT NULL,
  date_added DATETIME NOT NULL,
  PRIMARY KEY (customer_ip_id),
  CONSTRAINT fk_customer_ip_customer FOREIGN KEY (customer_id)
    REFERENCES oc_customer(customer_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_option_value_description
--
CREATE TABLE oc_option_value_description (
  option_value_id INT(11) NOT NULL,
  language_id INT(11) NOT NULL,
  option_id INT(11) NOT NULL,
  name VARCHAR(128) NOT NULL,
  CONSTRAINT fk_option_value_description_language FOREIGN KEY (language_id)
    REFERENCES oc_language(language_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_option_value_description_option FOREIGN KEY (option_id)
    REFERENCES oc_option(option_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_option_value_description_option_value FOREIGN KEY (option_value_id)
    REFERENCES oc_option_value(option_value_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AVG_ROW_LENGTH = 1170
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_order
--
CREATE TABLE oc_order (
  order_id INT(11) NOT NULL AUTO_INCREMENT,
  store_id INT(11) NOT NULL DEFAULT 0,
  customer_id INT(11) NOT NULL DEFAULT 0,
  customer_group_id INT(11) NOT NULL DEFAULT 0,
  shipping_country_id INT(11) NOT NULL,
  shipping_zone_id INT(11) NOT NULL,
  payment_country_id INT(11) NOT NULL,
  payment_zone_id INT(11) NOT NULL,
  order_status_id INT(11) NOT NULL DEFAULT 0,
  affiliate_id INT(11) NOT NULL,
  language_id INT(11) NOT NULL,
  currency_id INT(11) NOT NULL,
  invoice_no INT(11) NOT NULL DEFAULT 0,
  invoice_prefix VARCHAR(26) NOT NULL DEFAULT '',
  store_name VARCHAR(64) NOT NULL,
  store_url VARCHAR(255) NOT NULL,
  firstname VARCHAR(32) NOT NULL DEFAULT '',
  lastname VARCHAR(32) NOT NULL,
  email VARCHAR(96) NOT NULL,
  telephone VARCHAR(32) NOT NULL DEFAULT '',
  fax VARCHAR(32) NOT NULL DEFAULT '',
  shipping_firstname VARCHAR(32) NOT NULL,
  shipping_lastname VARCHAR(32) NOT NULL DEFAULT '',
  shipping_company VARCHAR(32) NOT NULL,
  shipping_address_1 VARCHAR(128) NOT NULL,
  shipping_address_2 VARCHAR(128) NOT NULL,
  shipping_city VARCHAR(128) NOT NULL,
  shipping_postcode VARCHAR(10) NOT NULL DEFAULT '',
  shipping_country VARCHAR(128) NOT NULL,
  shipping_zone VARCHAR(128) NOT NULL,
  shipping_address_format TEXT NOT NULL,
  shipping_method VARCHAR(128) NOT NULL DEFAULT '',
  shipping_code VARCHAR(128) NOT NULL DEFAULT '',
  payment_firstname VARCHAR(32) NOT NULL DEFAULT '',
  payment_lastname VARCHAR(32) NOT NULL DEFAULT '',
  payment_company VARCHAR(32) NOT NULL,
  payment_company_id VARCHAR(32) NOT NULL DEFAULT '',
  payment_tax_id VARCHAR(32) NOT NULL DEFAULT '',
  payment_address_1 VARCHAR(128) NOT NULL,
  payment_address_2 VARCHAR(128) NOT NULL,
  payment_city VARCHAR(128) NOT NULL,
  payment_postcode VARCHAR(10) NOT NULL DEFAULT '',
  payment_country VARCHAR(128) NOT NULL,
  payment_zone VARCHAR(128) NOT NULL,
  payment_address_format TEXT NOT NULL,
  payment_method VARCHAR(128) NOT NULL DEFAULT '',
  payment_code VARCHAR(128) NOT NULL DEFAULT '',
  `comment` TEXT NOT NULL,
  total DECIMAL(15, 4) NOT NULL DEFAULT 0.0000,
  commission DECIMAL(15, 4) NOT NULL,
  currency_code VARCHAR(3) NOT NULL,
  currency_value DECIMAL(15, 8) NOT NULL,
  date_added DATETIME NOT NULL,
  date_modified DATETIME NOT NULL,
  ip VARCHAR(15) NOT NULL DEFAULT '',
  forwarded_ip VARCHAR(15) NOT NULL DEFAULT '',
  user_agent VARCHAR(255) NOT NULL DEFAULT '',
  accept_language VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (order_id),
  CONSTRAINT fk_order_affiliate FOREIGN KEY (affiliate_id)
    REFERENCES oc_affiliate(affiliate_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_order_currency FOREIGN KEY (currency_id)
    REFERENCES oc_currency(currency_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_order_customer FOREIGN KEY (customer_id)
    REFERENCES oc_customer(customer_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_order_customer_group FOREIGN KEY (customer_group_id)
    REFERENCES oc_customer_group(customer_group_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_order_language FOREIGN KEY (language_id)
    REFERENCES oc_language(language_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_order_order_status FOREIGN KEY (order_status_id)
    REFERENCES oc_order_status(order_status_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_order_payment_country FOREIGN KEY (payment_country_id)
    REFERENCES oc_country(country_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_order_payment_zone FOREIGN KEY (payment_zone_id)
    REFERENCES oc_zone(zone_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_order_shipping_country FOREIGN KEY (shipping_country_id)
    REFERENCES oc_country(country_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_order_shipping_zone FOREIGN KEY (shipping_zone_id)
    REFERENCES oc_zone(zone_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_order_store FOREIGN KEY (store_id)
    REFERENCES oc_store(store_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_product
--
CREATE TABLE oc_product (
  product_id INT(11) NOT NULL AUTO_INCREMENT,
  model VARCHAR(64) NOT NULL,
  sku VARCHAR(64) NOT NULL,
  upc VARCHAR(12) NOT NULL,
  location VARCHAR(128) NOT NULL,
  quantity INT(4) NOT NULL DEFAULT 0,
  stock_status_id INT(11) NOT NULL,
  image VARCHAR(255) DEFAULT NULL,
  manufacturer_id INT(11) NOT NULL,
  shipping TINYINT(1) NOT NULL DEFAULT 1,
  price DECIMAL(15, 4) NOT NULL DEFAULT 0.0000,
  points INT(8) NOT NULL DEFAULT 0,
  tax_class_id INT(11) NOT NULL,
  date_available DATE NOT NULL,
  weight DECIMAL(15, 8) NOT NULL DEFAULT 0.00000000,
  weight_class_id INT(11) NOT NULL DEFAULT 0,
  length DECIMAL(15, 8) NOT NULL DEFAULT 0.00000000,
  width DECIMAL(15, 8) NOT NULL DEFAULT 0.00000000,
  height DECIMAL(15, 8) NOT NULL DEFAULT 0.00000000,
  length_class_id INT(11) NOT NULL DEFAULT 0,
  subtract TINYINT(1) NOT NULL DEFAULT 1,
  minimum INT(11) NOT NULL DEFAULT 1,
  sort_order INT(11) NOT NULL DEFAULT 0,
  status TINYINT(1) NOT NULL DEFAULT 0,
  date_added DATETIME DEFAULT NULL,
  date_modified DATETIME DEFAULT NULL,
  viewed INT(5) NOT NULL DEFAULT 0,
  PRIMARY KEY (product_id),
  CONSTRAINT fk_product_length_class FOREIGN KEY (length_class_id)
    REFERENCES oc_length_class(length_class_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_product_manufacturer FOREIGN KEY (manufacturer_id)
    REFERENCES oc_manufacturer(manufacturer_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_product_stock_status FOREIGN KEY (stock_status_id)
    REFERENCES oc_stock_status(stock_status_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_product_tax_class FOREIGN KEY (tax_class_id)
    REFERENCES oc_tax_class(tax_class_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_product_weight_class FOREIGN KEY (weight_class_id)
    REFERENCES oc_weight_class(weight_class_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 50
AVG_ROW_LENGTH = 862
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_tax_rate_to_customer_group
--
CREATE TABLE oc_tax_rate_to_customer_group (
  tax_rate_id INT(11) NOT NULL,
  customer_group_id INT(11) NOT NULL,
  CONSTRAINT fk_tax_rate_to_customer_group_customer_group FOREIGN KEY (customer_group_id)
    REFERENCES oc_customer_group(customer_group_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_tax_rate_to_customer_group_tax_rate FOREIGN KEY (tax_rate_id)
    REFERENCES oc_tax_rate(tax_rate_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_tax_rule
--
CREATE TABLE oc_tax_rule (
  tax_rule_id INT(11) NOT NULL AUTO_INCREMENT,
  tax_class_id INT(11) NOT NULL,
  tax_rate_id INT(11) NOT NULL,
  based VARCHAR(10) NOT NULL,
  priority INT(5) NOT NULL DEFAULT 1,
  PRIMARY KEY (tax_rule_id),
  CONSTRAINT fk_tax_rule_tax_class FOREIGN KEY (tax_class_id)
    REFERENCES oc_tax_class(tax_class_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_tax_rule_tax_rate FOREIGN KEY (tax_rate_id)
    REFERENCES oc_tax_rate(tax_rate_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 129
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_zone_to_geo_zone
--
CREATE TABLE oc_zone_to_geo_zone (
  zone_to_geo_zone_id INT(11) NOT NULL AUTO_INCREMENT,
  country_id INT(11) NOT NULL,
  geo_zone_id INT(11) NOT NULL,
  zone_id INT(11) DEFAULT NULL,
  date_added DATETIME NOT NULL,
  date_modified DATETIME NOT NULL,
  PRIMARY KEY (zone_to_geo_zone_id),
  CONSTRAINT fk_zone_to_geo_zone_country FOREIGN KEY (country_id)
    REFERENCES oc_country(country_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_zone_to_geo_zone_geo_zone FOREIGN KEY (geo_zone_id)
    REFERENCES oc_geo_zone(geo_zone_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_zone_to_geo_zone_zone FOREIGN KEY (zone_id)
    REFERENCES oc_zone(zone_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 66
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_affiliate_transaction
--
CREATE TABLE oc_affiliate_transaction (
  affiliate_transaction_id INT(11) NOT NULL AUTO_INCREMENT,
  affiliate_id INT(11) NOT NULL,
  order_id INT(11) NOT NULL,
  description TEXT NOT NULL,
  amount DECIMAL(15, 4) NOT NULL,
  date_added DATETIME NOT NULL,
  PRIMARY KEY (affiliate_transaction_id),
  CONSTRAINT fk_affiliate_transaction_affiliate FOREIGN KEY (affiliate_id)
    REFERENCES oc_affiliate(affiliate_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_affiliate_transaction_order FOREIGN KEY (order_id)
    REFERENCES oc_order(order_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_coupon_history
--
CREATE TABLE oc_coupon_history (
  coupon_history_id INT(11) NOT NULL AUTO_INCREMENT,
  coupon_id INT(11) NOT NULL,
  order_id INT(11) NOT NULL,
  customer_id INT(11) NOT NULL,
  amount DECIMAL(15, 4) NOT NULL,
  date_added DATETIME NOT NULL,
  PRIMARY KEY (coupon_history_id),
  CONSTRAINT fk_coupon_history_coupon FOREIGN KEY (coupon_id)
    REFERENCES oc_coupon(coupon_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_coupon_history_customer FOREIGN KEY (customer_id)
    REFERENCES oc_customer(customer_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_coupon_history_order FOREIGN KEY (order_id)
    REFERENCES oc_order(order_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_coupon_product
--
CREATE TABLE oc_coupon_product (
  coupon_product_id INT(11) NOT NULL AUTO_INCREMENT,
  coupon_id INT(11) NOT NULL,
  product_id INT(11) NOT NULL,
  PRIMARY KEY (coupon_product_id),
  CONSTRAINT fk_coupon_product_coupon FOREIGN KEY (coupon_id)
    REFERENCES oc_coupon(coupon_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_coupon_product_product FOREIGN KEY (product_id)
    REFERENCES oc_product(product_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_order_history
--
CREATE TABLE oc_order_history (
  order_history_id INT(11) NOT NULL AUTO_INCREMENT,
  order_id INT(11) NOT NULL,
  order_status_id INT(11) NOT NULL,
  notify TINYINT(1) NOT NULL DEFAULT 0,
  `comment` TEXT NOT NULL,
  date_added DATETIME NOT NULL,
  PRIMARY KEY (order_history_id),
  CONSTRAINT fk_order_history_order FOREIGN KEY (order_id)
    REFERENCES oc_order(order_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_order_history_order_status FOREIGN KEY (order_status_id)
    REFERENCES oc_order_status(order_status_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_order_product
--
CREATE TABLE oc_order_product (
  order_product_id INT(11) NOT NULL AUTO_INCREMENT,
  order_id INT(11) NOT NULL,
  product_id INT(11) NOT NULL,
  name VARCHAR(255) NOT NULL,
  model VARCHAR(24) NOT NULL,
  quantity INT(4) NOT NULL,
  price DECIMAL(15, 4) NOT NULL DEFAULT 0.0000,
  total DECIMAL(15, 4) NOT NULL DEFAULT 0.0000,
  tax DECIMAL(15, 4) NOT NULL DEFAULT 0.0000,
  reward INT(8) NOT NULL DEFAULT 0,
  PRIMARY KEY (order_product_id),
  CONSTRAINT fk_order_product_order FOREIGN KEY (order_id)
    REFERENCES oc_order(order_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_order_product_product FOREIGN KEY (product_id)
    REFERENCES oc_product(product_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_order_total
--
CREATE TABLE oc_order_total (
  order_total_id INT(10) NOT NULL AUTO_INCREMENT,
  order_id INT(11) NOT NULL,
  code VARCHAR(32) NOT NULL,
  title VARCHAR(255) NOT NULL DEFAULT '',
  `text` VARCHAR(255) NOT NULL DEFAULT '',
  value DECIMAL(15, 4) NOT NULL DEFAULT 0.0000,
  sort_order INT(3) NOT NULL,
  PRIMARY KEY (order_total_id),
  CONSTRAINT fk_order_total_order FOREIGN KEY (order_id)
    REFERENCES oc_order(order_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_product_attribute
--
CREATE TABLE oc_product_attribute (
  language_id INT(11) NOT NULL,
  product_id INT(11) NOT NULL,
  attribute_id INT(11) NOT NULL,
  `text` TEXT NOT NULL,
  CONSTRAINT fk_product_attribute_attribute FOREIGN KEY (attribute_id)
    REFERENCES oc_attribute(attribute_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_product_attribute_language FOREIGN KEY (language_id)
    REFERENCES oc_language(language_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_product_attribute_product FOREIGN KEY (product_id)
    REFERENCES oc_product(product_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AVG_ROW_LENGTH = 3276
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_product_description
--
CREATE TABLE oc_product_description (
  product_id INT(11) NOT NULL,
  language_id INT(11) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  meta_description VARCHAR(255) NOT NULL,
  meta_keyword VARCHAR(255) NOT NULL,
  CONSTRAINT fk_product_description_language FOREIGN KEY (language_id)
    REFERENCES oc_language(language_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_product_description_product FOREIGN KEY (product_id)
    REFERENCES oc_product(product_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_product_discount
--
CREATE TABLE oc_product_discount (
  product_discount_id INT(11) NOT NULL AUTO_INCREMENT,
  product_id INT(11) NOT NULL,
  customer_group_id INT(11) NOT NULL,
  quantity INT(4) NOT NULL DEFAULT 0,
  priority INT(5) NOT NULL DEFAULT 1,
  price DECIMAL(15, 4) NOT NULL DEFAULT 0.0000,
  date_start DATE NOT NULL,
  date_end DATE NOT NULL,
  PRIMARY KEY (product_discount_id),
  CONSTRAINT fk_product_discount_customer_group FOREIGN KEY (customer_group_id)
    REFERENCES oc_customer_group(customer_group_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_product_discount_product FOREIGN KEY (product_id)
    REFERENCES oc_product(product_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 441
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_product_image
--
CREATE TABLE oc_product_image (
  product_image_id INT(11) NOT NULL AUTO_INCREMENT,
  product_id INT(11) NOT NULL,
  image VARCHAR(255) DEFAULT NULL,
  sort_order INT(3) NOT NULL DEFAULT 0,
  PRIMARY KEY (product_image_id),
  CONSTRAINT fk_product_image_product FOREIGN KEY (product_id)
    REFERENCES oc_product(product_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 2352
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_product_option
--
CREATE TABLE oc_product_option (
  product_option_id INT(11) NOT NULL AUTO_INCREMENT,
  product_id INT(11) NOT NULL,
  option_id INT(11) NOT NULL,
  option_value TEXT NOT NULL,
  required TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (product_option_id),
  CONSTRAINT fk_product_option_option FOREIGN KEY (option_id)
    REFERENCES oc_option(option_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_product_option_product FOREIGN KEY (product_id)
    REFERENCES oc_product(product_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 227
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_product_related
--
CREATE TABLE oc_product_related (
  product_id INT(11) NOT NULL,
  related_id INT(11) NOT NULL,
  CONSTRAINT fk_product_related_product FOREIGN KEY (product_id)
    REFERENCES oc_product(product_id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT fk_product_related_product2 FOREIGN KEY (related_id)
    REFERENCES oc_product(product_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_product_reward
--
CREATE TABLE oc_product_reward (
  product_reward_id INT(11) NOT NULL AUTO_INCREMENT,
  product_id INT(11) NOT NULL DEFAULT 0,
  customer_group_id INT(11) NOT NULL DEFAULT 0,
  points INT(8) NOT NULL DEFAULT 0,
  PRIMARY KEY (product_reward_id),
  CONSTRAINT fk_product_reward_customer_group FOREIGN KEY (customer_group_id)
    REFERENCES oc_customer_group(customer_group_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_product_reward_product FOREIGN KEY (product_id)
    REFERENCES oc_product(product_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 547
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_product_special
--
CREATE TABLE oc_product_special (
  product_special_id INT(11) NOT NULL AUTO_INCREMENT,
  product_id INT(11) NOT NULL,
  customer_group_id INT(11) NOT NULL,
  priority INT(5) NOT NULL DEFAULT 1,
  price DECIMAL(15, 4) NOT NULL DEFAULT 0.0000,
  date_start DATE NOT NULL,
  date_end DATE NOT NULL,
  PRIMARY KEY (product_special_id),
  CONSTRAINT fk_product_special_customer_group FOREIGN KEY (customer_group_id)
    REFERENCES oc_customer_group(customer_group_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_product_special_product FOREIGN KEY (product_id)
    REFERENCES oc_product(product_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 440
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_product_tag
--
CREATE TABLE oc_product_tag (
  product_tag_id INT(11) NOT NULL AUTO_INCREMENT,
  product_id INT(11) NOT NULL,
  language_id INT(11) NOT NULL,
  tag VARCHAR(32) NOT NULL,
  PRIMARY KEY (product_tag_id),
  INDEX language_id (language_id),
  INDEX product_id (product_id),
  INDEX tag (tag),
  CONSTRAINT fk_product_tag_language FOREIGN KEY (language_id)
    REFERENCES oc_language(language_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_product_tag_product FOREIGN KEY (product_id)
    REFERENCES oc_product(product_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 343
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_product_to_category
--
CREATE TABLE oc_product_to_category (
  product_id INT(11) NOT NULL,
  category_id INT(11) NOT NULL,
  CONSTRAINT fk_product_to_category_category FOREIGN KEY (category_id)
    REFERENCES oc_category(category_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_product_to_category_product FOREIGN KEY (product_id)
    REFERENCES oc_product(product_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_product_to_download
--
CREATE TABLE oc_product_to_download (
  product_id INT(11) NOT NULL,
  download_id INT(11) NOT NULL,
  CONSTRAINT fk_product_to_download_download FOREIGN KEY (download_id)
    REFERENCES oc_download(download_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_product_to_download_product FOREIGN KEY (product_id)
    REFERENCES oc_product(product_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_product_to_layout
--
CREATE TABLE oc_product_to_layout (
  product_id INT(11) NOT NULL,
  layout_id INT(11) NOT NULL,
  store_id INT(11) NOT NULL,
  CONSTRAINT fk_product_to_layout_layout FOREIGN KEY (layout_id)
    REFERENCES oc_layout(layout_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_product_to_layout_product FOREIGN KEY (product_id)
    REFERENCES oc_product(product_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_product_to_layout_store FOREIGN KEY (store_id)
    REFERENCES oc_store(store_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_product_to_store
--
CREATE TABLE oc_product_to_store (
  product_id INT(11) NOT NULL,
  store_id INT(11) NOT NULL DEFAULT 0,
  CONSTRAINT fk_product_to_store_product FOREIGN KEY (product_id)
    REFERENCES oc_product(product_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_product_to_store_store FOREIGN KEY (store_id)
    REFERENCES oc_store(store_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_return
--
CREATE TABLE oc_return (
  return_id INT(11) NOT NULL AUTO_INCREMENT,
  order_id INT(11) NOT NULL,
  product_id INT(11) NOT NULL DEFAULT 0,
  customer_id INT(11) NOT NULL,
  return_status_id INT(11) NOT NULL,
  date_ordered DATE NOT NULL,
  date_added DATETIME NOT NULL,
  date_modified DATETIME NOT NULL,
  firstname VARCHAR(32) NOT NULL,
  lastname VARCHAR(32) NOT NULL,
  email VARCHAR(96) NOT NULL,
  telephone VARCHAR(32) NOT NULL,
  product VARCHAR(255) NOT NULL DEFAULT '',
  model VARCHAR(64) NOT NULL DEFAULT '',
  quantity INT(4) NOT NULL DEFAULT 0,
  opened TINYINT(1) NOT NULL DEFAULT 0,
  return_reason_id INT(11) NOT NULL DEFAULT 0,
  return_action_id INT(11) NOT NULL DEFAULT 0,
  `comment` TEXT DEFAULT NULL,
  PRIMARY KEY (return_id),
  CONSTRAINT fk_return_customer FOREIGN KEY (customer_id)
    REFERENCES oc_customer(customer_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_return_order FOREIGN KEY (order_id)
    REFERENCES oc_order(order_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_return_return_status FOREIGN KEY (return_status_id)
    REFERENCES oc_return_status(return_status_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_review
--
CREATE TABLE oc_review (
  review_id INT(11) NOT NULL AUTO_INCREMENT,
  product_id INT(11) NOT NULL,
  customer_id INT(11) NOT NULL,
  author VARCHAR(64) NOT NULL DEFAULT '',
  `text` TEXT NOT NULL,
  rating INT(1) NOT NULL,
  status TINYINT(1) NOT NULL DEFAULT 0,
  date_added DATETIME NOT NULL,
  date_modified DATETIME NOT NULL,
  PRIMARY KEY (review_id),
  CONSTRAINT fk_review_customer FOREIGN KEY (customer_id)
    REFERENCES oc_customer(customer_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_review_product FOREIGN KEY (product_id)
    REFERENCES oc_product(product_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_voucher
--
CREATE TABLE oc_voucher (
  voucher_id INT(11) NOT NULL AUTO_INCREMENT,
  order_id INT(11) NOT NULL,
  code VARCHAR(10) NOT NULL,
  from_name VARCHAR(64) NOT NULL,
  from_email VARCHAR(96) NOT NULL,
  to_name VARCHAR(64) NOT NULL,
  to_email VARCHAR(96) NOT NULL,
  message TEXT NOT NULL,
  amount DECIMAL(15, 4) NOT NULL,
  voucher_theme_id INT(11) NOT NULL,
  status TINYINT(1) NOT NULL DEFAULT 0,
  date_added DATETIME NOT NULL,
  PRIMARY KEY (voucher_id),
  CONSTRAINT fk_voucher_order FOREIGN KEY (order_id)
    REFERENCES oc_order(order_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_order_download
--
CREATE TABLE oc_order_download (
  order_download_id INT(11) NOT NULL AUTO_INCREMENT,
  order_id INT(11) NOT NULL,
  order_product_id INT(11) NOT NULL,
  name VARCHAR(64) NOT NULL DEFAULT '',
  filename VARCHAR(128) NOT NULL DEFAULT '',
  mask VARCHAR(128) NOT NULL DEFAULT '',
  remaining INT(3) NOT NULL DEFAULT 0,
  PRIMARY KEY (order_download_id),
  CONSTRAINT fk_order_download_order FOREIGN KEY (order_id)
    REFERENCES oc_order(order_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_order_download_order_product FOREIGN KEY (order_product_id)
    REFERENCES oc_order_product(order_product_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_product_option_value
--
CREATE TABLE oc_product_option_value (
  product_option_value_id INT(11) NOT NULL AUTO_INCREMENT,
  product_option_id INT(11) NOT NULL,
  product_id INT(11) NOT NULL,
  option_id INT(11) NOT NULL,
  option_value_id INT(11) NOT NULL,
  quantity INT(3) NOT NULL,
  subtract TINYINT(1) NOT NULL DEFAULT 0,
  price DECIMAL(15, 4) NOT NULL,
  price_prefix VARCHAR(1) NOT NULL,
  points INT(8) NOT NULL,
  points_prefix VARCHAR(1) NOT NULL,
  weight DECIMAL(15, 8) NOT NULL,
  weight_prefix VARCHAR(1) NOT NULL,
  PRIMARY KEY (product_option_value_id),
  CONSTRAINT fk_product_option_value_option FOREIGN KEY (option_id)
    REFERENCES oc_option(option_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_product_option_value_option_value FOREIGN KEY (option_value_id)
    REFERENCES oc_option_value(option_value_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_product_option_value_product FOREIGN KEY (product_id)
    REFERENCES oc_product(product_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_product_option_value_product_option FOREIGN KEY (product_option_id)
    REFERENCES oc_product_option(product_option_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 17
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_return_history
--
CREATE TABLE oc_return_history (
  return_history_id INT(11) NOT NULL AUTO_INCREMENT,
  return_id INT(11) NOT NULL,
  return_status_id INT(11) NOT NULL,
  notify TINYINT(1) NOT NULL DEFAULT 0,
  `comment` TEXT NOT NULL,
  date_added DATETIME NOT NULL,
  PRIMARY KEY (return_history_id),
  CONSTRAINT fk_return_history_return FOREIGN KEY (return_id)
    REFERENCES oc_return(return_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_return_history_return_status FOREIGN KEY (return_status_id)
    REFERENCES oc_return_status(return_status_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_voucher_history
--
CREATE TABLE oc_voucher_history (
  voucher_history_id INT(11) NOT NULL AUTO_INCREMENT,
  voucher_id INT(11) NOT NULL,
  order_id INT(11) NOT NULL,
  amount DECIMAL(15, 4) NOT NULL,
  date_added DATETIME NOT NULL,
  PRIMARY KEY (voucher_history_id),
  CONSTRAINT fk_voucher_history_order FOREIGN KEY (order_id)
    REFERENCES oc_order(order_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_voucher_history_voucher FOREIGN KEY (voucher_id)
    REFERENCES oc_voucher(voucher_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table oc_order_option
--
CREATE TABLE oc_order_option (
  order_option_id INT(11) NOT NULL AUTO_INCREMENT,
  order_id INT(11) NOT NULL,
  order_product_id INT(11) NOT NULL,
  product_option_id INT(11) NOT NULL,
  product_option_value_id INT(11) NOT NULL DEFAULT 0,
  name VARCHAR(255) NOT NULL,
  value TEXT NOT NULL,
  type VARCHAR(32) NOT NULL,
  PRIMARY KEY (order_option_id),
  CONSTRAINT fk_order_option_order FOREIGN KEY (order_id)
    REFERENCES oc_order(order_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_order_option_order_product FOREIGN KEY (order_product_id)
    REFERENCES oc_order_product(order_product_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_order_option_product_option FOREIGN KEY (product_option_id)
    REFERENCES oc_product_option(product_option_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_order_option_product_option_value FOREIGN KEY (product_option_value_id)
    REFERENCES oc_product_option_value(product_option_value_id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_bin;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;