INSERT INTO `setting` (`store_id`, `group`, `key`, `value`, `serialized`) VALUES
(1, 'config', 'config_google_analytics', '', 0),
(1, 'config', 'config_error_filename', 'error.txt', 0),
(1, 'config', 'config_error_log', '1', 0),
(1, 'config', 'config_error_display', '1', 0),
(1, 'config', 'config_compression', '0', 0),
(1, 'config', 'config_encryption', '12345', 0),
(1, 'config', 'config_maintenance', '0', 0),
(1, 'config', 'config_account_mail', '0', 0),
(1, 'config', 'config_alert_emails', '', 0),
(1, 'config', 'config_use_ssl', '0', 0),
(1, 'config', 'config_seo_url', '0', 0),
(1, 'config', 'config_alert_mail', '0', 0),
(1, 'config', 'config_smtp_username', '', 0),
(1, 'config', 'config_smtp_password', '', 0),
(1, 'config', 'config_smtp_port', '25', 0),
(1, 'config', 'config_smtp_timeout', '5', 0),
(1, 'config', 'config_smtp_host', '', 0),
(1, 'config', 'config_image_cart_height', '80', 0),
(1, 'config', 'config_mail_protocol', 'mail', 0),
(1, 'config', 'config_mail_parameter', '', 0),
(1, 'config', 'config_image_wishlist_height', '50', 0),
(1, 'config', 'config_image_cart_width', '80', 0),
(1, 'config', 'config_image_wishlist_width', '50', 0),
(1, 'config', 'config_image_compare_height', '90', 0),
(1, 'config', 'config_image_compare_width', '90', 0),
(1, 'config', 'config_image_related_height', '80', 0),
(1, 'config', 'config_image_related_width', '80', 0),
(1, 'config', 'config_image_additional_height', '74', 0),
(1, 'config', 'config_image_additional_width', '74', 0),
(1, 'config', 'config_image_manufacturer_height', '80', 0),
(1, 'config', 'config_image_manufacturer_width', '80', 0),
(1, 'config', 'config_image_category_height', '80', 0),
(1, 'config', 'config_image_category_width', '80', 0),
(1, 'config', 'config_image_product_height', '80', 0),
(1, 'config', 'config_image_product_width', '80', 0),
(1, 'config', 'config_image_popup_height', '500', 0),
(1, 'config', 'config_image_popup_width', '500', 0),
(1, 'config', 'config_image_thumb_height', '228', 0),
(1, 'config', 'config_image_thumb_width', '228', 0),
(1, 'config', 'config_icon', 'data/cart.png', 0),
(1, 'config', 'config_logo', 'data/logo.png', 0),
(1, 'config', 'config_cart_weight', '1', 0),
(1, 'config', 'config_upload_allowed', 'jpg, JPG, jpeg, gif, png, txt', 0),
(1, 'config', 'config_review_status', '1', 0),
(1, 'config', 'config_download', '1', 0),

(1, 'config', 'config_guest_checkout', '1', 0),
(1, 'config', 'config_customer_approval', '0', 0),
(1, 'config', 'config_customer_price', '0', 0),

(1, 'config', 'config_invoice_prefix', 'INV', 0),

(1, 'config', 'config_admin_limit', '20', 0),
(1, 'config', 'config_catalog_limit', '15', 0),

(1, 'config', 'config_title', 'Your Store', 0),
(1, 'config', 'config_name', 'Your Store', 0),
(1, 'config', 'config_owner', 'Your Name', 0),
(1, 'config', 'config_address', 'Address 1', 0),
(1, 'config', 'config_email', 'your@store.com', 0),
(1, 'config', 'config_telephone', '123456789', 0),
(1, 'config', 'config_fax', '', 0),
(1, 'config', 'config_meta_description', 'My Store', 0),

(1, 'config', 'config_template', 'default', 0),
(1, 'config', 'config_language', 'en', 0),
(1, 'config', 'config_admin_language', 'en', 0);
